# Form implementation generated from reading ui file 'carwash.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from ui import Ui_mainui
from PyQt5.QtWidgets import QApplication, QFrame, QGraphicsScene
import sys

if __name__ == "__main__":
    app = QApplication(sys.argv)
    screen = app.primaryScreen()
    screen_size = screen.size()
    print(screen_size)
    Frame = QFrame()
    Frame.setGeometry(0, 0, screen_size.width(), screen_size.height())
    Frame.setWindowTitle("Car Wash")
    ui = Ui_mainui()
    ui.setupUi(Frame)
    
    Frame.showFullScreen()

    sys.exit(app.exec())