# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carwash.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtCore import QUrl

class Ui_mainui(object):
    def setupUi(self, mainui):
        mainui.setObjectName("mainui")
        mainui.setWindowModality(QtCore.Qt.ApplicationModal)
        mainui.resize(1920, 1080)
        self.layoutWidget = QtWidgets.QWidget(mainui)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.layoutWidget.setObjectName("layoutWidget")
        
        # Create QGridLayout
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        # Create QLabel label_2
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(54)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        
        # Create QLabel label_3
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(54)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        
        # Updated to use QWebEngineView
        self.webView = QWebEngineView(self.layoutWidget)
        self.webView.setUrl(QtCore.QUrl("https://www.youtube.com/watch?v=vr0htZlAQbk&feature=youtu.be"))
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 0, 0, 1, 3)
        self.gridLayout.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.gridLayout.setRowStretch(0, 1)
        
        # Create QLabel label
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(54)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(mainui)
        QtCore.QMetaObject.connectSlotsByName(mainui)

    def retranslateUi(self, mainui):
        _translate = QtCore.QCoreApplication.translate
        mainui.setWindowTitle(_translate("mainui", "Frame"))
        self.label_2.setText(_translate("mainui", "3:00"))
        self.label_3.setText(_translate("mainui", "SUV"))
        self.label.setText(_translate("mainui", "1000 so\'m"))
